TMS_TurfManager/urls.py
from django.urls import path
from . import views
app_name = 'manager'

urlpatterns = [
    path('ManagerHome/', views.Managerhome, name = "mhomepage"),
    path('ManagerTurf/', views.Managerturf, name = "mturf"),
    path('ManagerConfirm/', views.Managerconfirm, name = "mbookconfirm"),
    path('ManagerCancel/', views.Managercancel, name = "mcancelbook"),
    path('ManagerAccept/', views.Manageraccept, name = "macceptbook"),
    path('ManagerBookings/', views.Managerbookings, name = "mbookhistory"),
    path('ManagerReviews/', views.Managerreviews, name = "mturfreview"),
    path('ManagerEditturf/<int:turf_id>', views.Managereditturf, name = "mturfedit"),
    path('ManagerAddimage/', views.Manageraddimage, name = "mturfimage"),
    path('ManagerEditprofile/<int:edit_id>', views.Managereditprofile, name = "meditprofile"),
]

TMS_admin/urls.py
from django.urls import path
from . import views
app_name = 'appadmin'

urlpatterns = [
    path('Amalgamation/', views.Homepage, name = "homepage"),
    path('Amalgamation1/', views.Homepage2, name = "homepage2"),
    path('LoginUser/', views.Loginuser, name = "loginuser"),
    path('LoginManager/', views.Loginmanager, name = "loginmanager"),
    path('UserLogout/', views.Userlogout, name= "userlogout"),
    path('ManagerLogout/', views.Managerlogout, name= "managerlogout"),
    path('Contact/', views.Turfrequest, name = "turfrequest"),
    path('Register/', views.Register, name = "register"),
    path('Adminlogin/', views.AdminLogin, name = "admlogin"),
    path('Adminhome/', views.AdminHome, name = "admhome"),
    path('AdminLogout/', views.Adminlogout, name= "admlogout"),
    path('AdminAddmngr/<int:mn_id>', views.Adminaddmngr, name = "admaddmngr"),
    path('Adminrejectmngr/<int:mn_id>', views.Adminrejectmngr, name = "admreject"),
    path('AdminAddturf/', views.Adminaddturf, name = "admaddturf"),
    path('AdminFeedbacks/', views.Adminfeedbacks, name = "admfeedback"),
    path('AdminManagers/', views.Adminmanagers, name = "admmanagers"),
    path('AdminRejManagers/', views.Adminrejmanagers, name = "admrejmanagers"),
    path('AdminUsers/', views.Adminusers, name = "admusers"),
    path('AdminTurfs/', views.Adminturfs, name = "admturfs"),
    path('Adminimages/<int:turfid>', views.Adminviewimages, name = "admturfimages"),
    path('AdminRequests/', views.Adminrequests, name = "admrequests"),
]

TMS_user/urls.py
from django.urls import path
from . import views
app_name = 'user'

urlpatterns = [
    path('UserHome/', views.Userhome, name = "uhomepage"),
    path('UserSearch/', views.Usersearch, name = "usearchturf"),
    path('UserSearchlist/', views.Searchlist, name = "usearchlist"),
    path('UserSearchDetail/<int:turfid>', views.Usersearchdetail, name = "usearchdetail"),
    path('UserConfirm/<int:turfid>', views.Userconfirm, name = "uconfirmturf"),
    path('UserReview/<int:turfid>', views.Userreview, name = "ureview"),
    path('UserBookings/', views.Userbookings, name = "ubookings"),
    path('UserPayment/', views.Userpayment, name = "upayment"),
    path('UserFeedback/', views.Userfeedback, name = "ufeedback"),
    path('UserEditprofile/<int:edit_id>', views.Usereditprofile, name = "ueditprofile"),
]

TurfManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("TMS_admin/", include ('TMS_admin.urls')),
    path("TMS_TurfManager/", include ('TMS_TurfManager.urls')),
    path("TMS_user/", include ('TMS_user.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TMS_TurfManager/models.py
from django.db import models

# Create your models here.

TMS_TurfManager/views.py
from django.shortcuts import render,redirect
from . models import *
from TMS_admin.models import Managerlist
from TMS_admin.models import Turfimages
from TMS_admin.views import *
# Create your views here.

def Managerhome(request):
    if 'managerlog_id' in request.session:
        id = request.session['managerlog_id']
        manager = Managerlist.objects.get(id = id)
        return render (request, "managerpages/Manager_profile.html", {'manager_data': manager})
    else:
        return render (request, "adminpages/LoginManager.html")
    
def Managerturf(request):
    if 'managerlog_id' in request.session:
        id = request.session['managerlog_id']
        manager = Managerlist.objects.get(id = id)
        image = Turfimages.objects.filter(manager_id = id)
        return render (request, "managerpages/manager_turf.html", {'manager_data': manager, 't_image': image})
    else:
        return render (request, "adminpages/LoginManager.html")

def Managerconfirm(request):
    if 'managerlog_id' in request.session:
        id = request.session['managerlog_id']
        manager = Managerlist.objects.get(id = id)
        booking = Bookings.objects.filter(mn_id_id = id, b_status = 'Pending')
        return render (request, "managerpages/manag_confbook.html", {'manager_data': manager, 'bookings': booking})
    else:
        return render (request, "adminpages/LoginManager.html")

def Managerbookings(request):
    if 'managerlog_id' in request.session:
        id = request.session['managerlog_id']
        manager = Managerlist.objects.get(id = id)
        booking = Bookings.objects.filter(mn_id_id = id)
        return render (request, "managerpages/manag_bookhist.html", {'manager_data': manager, 'bookings': booking})
    else:
        return render (request, "adminpages/LoginManager.html")

def Managercancel(request):
    if 'managerlog_id' in request.session:
        id = request.session['managerlog_id']
        status = 'Cancelled'
        payment = 'NA'
        Bookings.objects.filter(mn_id_id = id).update(b_status = status, b_pstatus = payment)
        return redirect ('manager:mbookhistory')
    else:
        return render (request, "adminpages/LoginManager.html")
    
def Manageraccept(request):
    if 'managerlog_id' in request.session:
        id = request.session['managerlog_id']
        status = 'Confirmed'
        payment = 'Pending'
        Bookings.objects.filter(mn_id_id = id).update(b_status = status, b_pstatus = payment)
        return redirect ('manager:mbookhistory')
    else:
        return render (request, "adminpages/LoginManager.html")    

def Managerreviews(request):
    if 'managerlog_id' in request.session:
        id = request.session['managerlog_id']
        manager = Managerlist.objects.get(id = id)
        review = Turfreview.objects.filter(m_id_id = id)
        return render (request, "managerpages/manag_turfreview.html", {'manager_data': manager, 'reviews': review})
    else:
        return render (request, "adminpages/LoginManager.html")

def Managereditturf(request, turf_id):
    if 'managerlog_id' in request.session:
        if request.method == "POST":
            t_name = request.POST['turfname1']
            t_location = request.POST['turfloc1']
            t_cost = request.POST['turfcost1']
            t_desc = request.POST['turfdesc1']
            Managerlist.objects.filter(id = turf_id).update(man_turfname = t_name, man_turfloc = t_location, turf_cost = t_cost, turf_desc = t_desc)
            return redirect('manager:mturf')
        else:
            manager = Managerlist.objects.get(id = turf_id)    
            return render (request, "managerpages/manag_editturf.html", {'manager_data': manager})
    else:
        return render (request, "adminpages/LoginManager.html")
    
def Manageraddimage(request):
    if 'managerlog_id' in request.session:
        m_id = request.session['managerlog_id']
        if request.method == "POST":
            t_image = request.FILES['image']
            Turf = Turfimages(images = t_image, manager_id_id = m_id)
            Turf.save()
            return redirect('manager:mturf')
        else:
            manager = Managerlist.objects.get(id = m_id)
            return render (request, "managerpages/manag_turfimage.html", {'manager_data': manager})
    else:
        return render (request, "adminpages/LoginManager.html")    

def Managereditprofile(request,edit_id):
    if 'managerlog_id' in request.session:
        if request.method == "POST":
            m_name = request.POST['mngname']
            m_contact = request.POST['mngphone']
            m_email = request.POST['mngemail']
            m_username = request.POST['mngusername']
            m_password = request.POST['mngnewpass']
            Managerlist.objects.filter(id = edit_id).update(man_name=m_name, man_email=m_email, man_contact=m_contact, man_username=m_username, man_password=m_password)
            return redirect ('manager:mhomepage')
        else:    
            mng_data = Managerlist.objects.get(id = edit_id)
            return render (request, "managerpages/managerprofile2.html", {'mng': mng_data})
            
    else:
        return render (request, "adminpages/LoginManager.html")

TMS_TurfManager/templates/managerpages/Manager_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manager Home</title>
    <link href="{% static '/css/proj2.css' %}" rel="stylesheet"/>
    <link rel = "icon" href = "https://cdn-icons-png.flaticon.com/128/8188/8188380.png" width="25px" height="20px" type = "image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
  <header>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-dark" style=" background-color: #0a0a0a">
          <a class="navbar-brand" href="{% url 'appadmin:homepage2' %}"><img src="{% static '/images/amalgamation_logo.jpg' %}" alt="" width="30" height="40"><b> Amalgamation</b></a>
        </nav>
    </div>
  </header>  
  <div class="welcome_user">
    <nav class="navbar navbar-light">
      <a class="navbar-brand">Hello {{manager_data.man_name}}</a>
      <form class="form-inline">
        <li><a href="{% url 'appadmin:homepage2' %}">Home</a></li>
        <li><a href="{% url 'manager:mhomepage' %}">Dashboard </a></li>
        <a href="{% url 'appadmin:managerlogout' %}"><button class="btn btn-outline-success my-2 my-sm-0" type="button">Logout</button></a>
      </form>
    </nav>
  </div>
  <div class="container-fluid managerhome">
    <div class="row">
      <div class="col-md-12 manager_home">
        <ul>
          <li><a href="{% url 'appadmin:homepage2' %}">Home</a></li>
          <li><a href="{% url 'manager:mturf' %}">My Turf</a></li>
          <li><a href="{% url 'manager:mbookconfirm' %}">Confirm Bookings</a></li>
          <li><a href="{% url 'manager:mbookhistory' %}">Booking History</a></li>
          <li><a href="{% url 'manager:mturfreview' %}">Turf Reviews</a></li>
          <li><a href="{% url 'manager:meditprofile' manager_data.id %}">Edit Profile</a></li>
          <li><a href="{% url 'appadmin:managerlogout' %}">Logout</a></li>
        </ul>
      </div>
    </div>  
  </div>
  <div class="container- my-3">
    <footer class="text-center text-lg-start text-white" style="background:linear-gradient(to right, #568EE3, #B368ED);">
      <div class="container p-4 pb-0">
        <section class="">
          <div class="row">
            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">
                About Us
              </h6>
              <p style="font-family: Arial, Helvetica, sans-serif;">
                We are one of the leading online turf booking platform based in Kerala.
                Choose the turf of your choice and enjoy the time with your friends - We can make it simple for you.
                So join us and have the blast!!! 
              </p>
            </div>
            <hr class="w-100 clearfix d-md-none" />
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Quick Links</h6>
              <p class="Footers">
                <a class="text-white" href="{% url 'appadmin:homepage2' %}">Home</a>
              </p>
              <p>
                <a class="text-white">Login</a>
              </p>
              <p>
                <a class="text-white">Book Now</a>
              </p>
            </div>
            <hr class="w-100 clearfix d-md-none" />
            <hr class="w-100 clearfix d-md-none" />
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Contact Us</h6>
              <p><i class="fas fa-pen mr-3"></i> Amalgamation</p>
                <p><i class="fas fa-home mr-3"></i> Taliparamba, Kannur, Kerala</p>
                <p><i class="fas fa-envelope mr-3"></i> amalg@gmail.com</p>
                <p><i class="fas fa-phone mr-3"></i> + 7012 39 1939</p>
            </div>
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Follow us</h6>
  
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #3b5998"
                 href="#!"
                 role="button">
                 <i class="fab fa-facebook-f"></i>
              </a>
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #55acee"
                 href="#!"
                 role="button">
                 <i class="fab fa-twitter"></i>
              </a>
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #dd4b39"
                 href="#!"
                 role="button">
                 <i class="fab fa-google"></i>
              </a>
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #ac2bac"
                 href="#!"
                 role="button">
                 <i class="fab fa-instagram"></i>
              </a>
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #0082ca"
                 href="#!"
                 role="button">
                 <i class="fab fa-linkedin-in"></i>
              </a>
            </div>
          </div>
        </section>
      </div>
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2022 Copyright:
        <a class="text-white" href="#">Amalgamation.com</a>
      </div>
    </footer>
  </div>
   
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>

TMS_TurfManager/templates/managerpages/manag_confbook.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm User Requests</title>
    <link href="{% static '/css/proj2.css' %}" rel="stylesheet"/>
    <link rel = "icon" href = "https://cdn-icons-png.flaticon.com/128/5681/5681932.png" width="25px" height="20px" type = "image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
</head>
<body>
  <header>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-dark" style=" background-color: #0a0a0a">
          <a class="navbar-brand" href="{% url 'appadmin:homepage2' %}"><img src="{% static '/images/amalgamation_logo.jpg' %}" alt="" width="30" height="40"><b> Amalgamation</b></a>
        </nav>
    </div>
  </header>  
  <div class="welcome_user">
    <nav class="navbar navbar-light">
      <a class="navbar-brand">Hello {{manager_data.man_name}}</a>
      <form class="form-inline">
        <li><a href="{% url 'appadmin:homepage2' %}">Home</a></li>
        <li><a href="{% url 'manager:mhomepage' %}">Dashboard </a></li>
        <a href="{% url 'appadmin:managerlogout' %}"><button class="btn btn-outline-success my-2 my-sm-0" type="button">Logout</button></a>
      </form>
    </nav>
  </div>
  <div class="container-fluid managerhome">
    <div class="row">
      <h2>Confirm Bookings</h2>
      <div class="col-md-12 managerconfirm1">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Contact Number</th>
              <th scope="col">Requested Turf</th>
              <th scope="col">Date</th>
              <th scope="col">Time Slot</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            {% for book in bookings %}
            <tr>
              <th scope="row">{{book.id}}</th>
              <td>{{book.b_name}}</td>
              <td>{{book.b_contact}}</td>
              <td>{{book.b_turf}}</td>
              <td>{{book.b_date|date:'d/m/Y'}}</td>
              <td>{{book.b_tst|time:"g:i A"}} - {{book.b_tend|time:"g:i A"}}</td>
              <td><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#b{{book.pk}}"><i class="fas fa-circle-check"> Accept</i></button>
                <a href="{% url 'manager:mcancelbook' %}"><button type="button" class="btn btn-secondary"><i class="fa-sharp fa-solid fa-times-circle"> Cancel</i></button></a>
              </td>
                <div class="modal fade" id="b{{book.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content confbutton">
                      <div class="modal-header ">
                        <h5 class="modal-title" id="exampleModalCenterTitle">Confirm Booking</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        {{book.b_name}} ; {{book.b_turf}} ; {{book.b_date|date:'d/m/Y'}} ; {{book.b_tst|time:"g:i A"}} - {{book.b_tend|time:"g:i A"}}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <a href="{% url 'manager:macceptbook' %}"><button type="button" class="btn btn-success">Generate Bill</button></a>
                      </div>
                    </div>
                  </div>
                </div>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>  
  </div>
  <div class="container- my-3">
    <footer class="text-center text-lg-start text-white" style="background:linear-gradient(to right, #568EE3, #B368ED);">
      <div class="container p-4 pb-0">
        <section class="">
          <div class="row">
            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">
                About Us
              </h6>
              <p style="font-family: Arial, Helvetica, sans-serif;">
                We are one of the leading online turf booking platform based in Kerala.
                Choose the turf of your choice and enjoy the time with your friends - We can make it simple for you.
                So join us and have the blast!!! 
              </p>
            </div>
            <hr class="w-100 clearfix d-md-none" />
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Quick Links</h6>
              <p class="Footers">
                <a class="text-white" href="{% url 'appadmin:homepage2' %}">Home</a>
              </p>
              <p>
                <a class="text-white">Login</a>
              </p>
              <p>
                <a class="text-white">Book Now</a>
              </p>
            </div>
            <hr class="w-100 clearfix d-md-none" />
            <hr class="w-100 clearfix d-md-none" />
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Contact Us</h6>
              <p><i class="fas fa-pen mr-3"></i> Amalgamation</p>
                <p><i class="fas fa-home mr-3"></i> Taliparamba, Kannur, Kerala</p>
                <p><i class="fas fa-envelope mr-3"></i> amalg@gmail.com</p>
                <p><i class="fas fa-phone mr-3"></i> + 7012 39 1939</p>
            </div>
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Follow us</h6>
  
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #3b5998"
                 href="#!"
                 role="button">
                 <i class="fab fa-facebook-f"></i>
              </a>
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #55acee"
                 href="#!"
                 role="button">
                 <i class="fab fa-twitter"></i>
              </a>
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #dd4b39"
                 href="#!"
                 role="button">
                 <i class="fab fa-google"></i>
              </a>
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #ac2bac"
                 href="#!"
                 role="button">
                 <i class="fab fa-instagram"></i>
              </a>
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #0082ca"
                 href="#!"
                 role="button">
                 <i class="fab fa-linkedin-in"></i>
              </a>
            </div>
          </div>
        </section>
      </div>
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2022 Copyright:
        <a class="text-white" href="#">Amalgamation.com</a>
      </div>
    </footer>
  </div>
  
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>