TMS_admin/urls.py
from django.urls import path
from . import views
app_name = 'appadmin'

urlpatterns = [
    path('Amalgamation/', views.Homepage, name = "homepage"),
    path('Amalgamation1/', views.Homepage2, name = "homepage2"),
    path('LoginUser/', views.Loginuser, name = "loginuser"),
    path('LoginManager/', views.Loginmanager, name = "loginmanager"),
    path('UserLogout/', views.Userlogout, name= "userlogout"),
    path('ManagerLogout/', views.Managerlogout, name= "managerlogout"),
    path('Contact/', views.Turfrequest, name = "turfrequest"),
    path('Register/', views.Register, name = "register"),
    path('Adminlogin/', views.AdminLogin, name = "admlogin"),
    path('Adminhome/', views.AdminHome, name = "admhome"),
    path('AdminLogout/', views.Adminlogout, name= "admlogout"),
    path('AdminAddmngr/<int:mn_id>', views.Adminaddmngr, name = "admaddmngr"),
    path('Adminrejectmngr/<int:mn_id>', views.Adminrejectmngr, name = "admreject"),
    path('AdminAddturf/', views.Adminaddturf, name = "admaddturf"),
    path('AdminFeedbacks/', views.Adminfeedbacks, name = "admfeedback"),
    path('AdminManagers/', views.Adminmanagers, name = "admmanagers"),
    path('AdminRejManagers/', views.Adminrejmanagers, name = "admrejmanagers"),
    path('AdminUsers/', views.Adminusers, name = "admusers"),
    path('AdminTurfs/', views.Adminturfs, name = "admturfs"),
    path('Adminimages/<int:turfid>', views.Adminviewimages, name = "admturfimages"),
    path('AdminRequests/', views.Adminrequests, name = "admrequests"),
]

TMS_user/urls.py
from django.urls import path
from . import views
app_name = 'user'

urlpatterns = [
    path('UserHome/', views.Userhome, name = "uhomepage"),
    path('UserSearch/', views.Usersearch, name = "usearchturf"),
    path('UserSearchlist/', views.Searchlist, name = "usearchlist"),
    path('UserSearchDetail/<int:turfid>', views.Usersearchdetail, name = "usearchdetail"),
    path('UserConfirm/<int:turfid>', views.Userconfirm, name = "uconfirmturf"),
    path('UserReview/<int:turfid>', views.Userreview, name = "ureview"),
    path('UserBookings/', views.Userbookings, name = "ubookings"),
    path('UserPayment/', views.Userpayment, name = "upayment"),
    path('UserFeedback/', views.Userfeedback, name = "ufeedback"),
    path('UserEditprofile/<int:edit_id>', views.Usereditprofile, name = "ueditprofile"),
]

TurfManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("TMS_admin/", include ('TMS_admin.urls')),
    path("TMS_TurfManager/", include ('TMS_TurfManager.urls')),
    path("TMS_user/", include ('TMS_user.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TMS_admin/models.py
from django.db import models

# Create your models here.
class Adminlog(models.Model):
    admin_name = models.TextField(max_length=50, db_column='name')
    admin_pass = models.TextField(max_length=50, db_column='pswd')

    class Meta:
        db_table="adminlogin"	

class Managerlist(models.Model):
    man_name = models.TextField(max_length=50, db_column='name')
    man_email = models.TextField(max_length=50, db_column='email')
    man_contact = models.TextField(max_length=50, db_column='contact')
    man_turfname = models.TextField(max_length=50, db_column='turf')
    man_turfloc = models.TextField(max_length=50, db_column='loc')
    man_username = models.TextField(max_length=50, db_column='usnam')
    man_password = models.TextField(max_length=50, db_column='pswd')
    man_status = models.TextField(max_length=50, db_column='status')    
    turf_desc = models.TextField(max_length=500, null=True, db_column='desc')
    turf_cost = models.TextField(max_length=50, null=True, db_column='cost')

    class Meta:
        db_table="managerlist"

class Userlist(models.Model):
    user_name = models.TextField(max_length=50, db_column='name')
    user_email = models.TextField(max_length=50, db_column='email')
    user_mobile = models.TextField(max_length=50, db_column='mobile')
    user_username = models.TextField(max_length=50, db_column='usnam')
    user_password = models.TextField(max_length=50, db_column='pswd')
    user_confpassword = models.TextField(max_length=50, db_column='cpswd')    

    class Meta:
        db_table="userlist"

class Turfimages(models.Model):
    manager_id = models.ForeignKey(Managerlist, on_delete=models.CASCADE, db_column='m_id')
    images = models.ImageField(upload_to='images/', db_column='images')

    class Meta:
        db_table="turfimages"

TMS_user/models.py
from django.db import models
from TMS_admin.models import *

# Create your models here.

class Feedbacks(models.Model):
    f_name = models.TextField(max_length=50,db_column='name')
    f_email = models.TextField(max_length=50,db_column='email')
    f_contact = models.TextField(max_length=50, db_column='contact')
    f_message = models.TextField(max_length=100, db_column='msg')

    class Meta:
        db_table="feedbacks"

class Turfreview(models.Model):
    u_id = models.ForeignKey(Userlist, on_delete=models.CASCADE, db_column='userid')
    m_id = models.ForeignKey(Managerlist, on_delete=models.CASCADE, db_column='turfid')
    r_name = models.TextField(max_length=50, db_column='name')
    r_contact = models.TextField(max_length=50, db_column='contact')
    r_message = models.TextField(max_length=100, null=False, db_column='msg')   

    class Meta:
        db_table="reviews"

class Bookings(models.Model):
    us_id = models.ForeignKey(Userlist, on_delete=models.CASCADE, db_column='userid')    
    mn_id = models.ForeignKey(Managerlist, on_delete=models.CASCADE, db_column='mngid') 
    b_name = models.TextField(max_length=50, db_column='name')
    b_contact = models.TextField(max_length=20, db_column='contact')
    b_turf = models.TextField(max_length=50, db_column='turf')
    b_cost = models.TextField(max_length=10, db_column='cost')
    b_date = models.DateField(db_column='date')
    b_tst = models.TimeField(db_column='timefrom')
    b_tend = models.TimeField(db_column='timeto')
    b_tcost = models.TextField(max_length=10, db_column='tcost')
    b_status = models.TextField(max_length=50, db_column='status')
    b_pstatus = models.TextField(max_length=50, db_column='payment')

    class Meta:
        db_table="bookings"

TMS_user/views.py
from django.shortcuts import render, redirect
from . models import *
from TMS_admin.models import Userlist
from TMS_admin.models import Managerlist
from TMS_admin.models import Turfimages

# Create your views here.

def Userhome(request):
    if 'userlog_id' in request.session:
        userid = request.session['userlog_id']
        userlog = Userlist.objects.get(id = userid)
        return render (request, "userpages/user_profile.html", {'user': userlog})
    else:
        return render (request, "adminpages/LoginUser.html")

def Usersearch(request):
    if 'userlog_id' in request.session:
        userid = request.session['userlog_id']
        userlog = Userlist.objects.get(id = userid)
        turflist = Managerlist.objects.filter(man_status = 'accepted').order_by('id')
        turfimages = Turfimages.objects.filter(manager_id = userid)    
        review = Turfreview.objects.filter(m_id_id = userid)
        # for img in turflist.turfimages_set.all:
        #     print("hello")
        #     print(img)    
        return render (request, "userpages/user_srchturf.html", {'user': userlog, 'turf': turflist, 'image':turfimages, 'reviews': review})
    else:
        return render (request, "adminpages/LoginUser.html")
    
def Searchlist(request):
    if 'userlog_id' in request.session:
        userid = request.session['userlog_id']
        userlog = Userlist.objects.get(id = userid)
        searchname = request.POST['search']
        turflist = Managerlist.objects.filter(man_turfname__icontains=searchname, man_status = 'accepted').order_by('id')
        if searchname == "":
            return redirect('user:usearchturf')
        else:
            return render (request, "userpages/user_searchlist.html", {'user': userlog, 'turf1': turflist})
    else:
        return render (request, "adminpages/LoginUser.html")    
    
def Usersearchdetail(request,turfid):
    if 'userlog_id' in request.session:
        userid = request.session['userlog_id']
        userlog = Userlist.objects.get(id = userid)
        turflist = Managerlist.objects.get(id = turfid)
        turfimages = Turfimages.objects.filter(manager_id = turfid)    
        review = Turfreview.objects.filter(m_id_id = turfid)
        return render (request, "userpages/user_searchdetail.html", {'user': userlog, 'turf': turflist, 'image':turfimages, 'reviews': review})
    else:
        return render (request, "adminpages/LoginUser.html")    
    
def Userreview(request,turfid):
    if 'userlog_id' in request.session:
        userid = request.session['userlog_id']
        userlog = Userlist.objects.get(id = userid)
        turf = Managerlist.objects.get(id = turfid)
        rmessage = ""
        if request.method == "POST":
            name = request.POST['revname']
            contact = request.POST['revcontact']
            message = request.POST['revmessage']
            us_review = Turfreview(u_id_id = userid, m_id_id = turf.id, r_name = name, r_contact = contact, r_message = message)
            us_review.save()
            if us_review:
                rmessage = "Thanks for your valuable feedback"
            else:
                rmessage = "error"
        return render (request, "userpages/user_review.html", {'user': userlog, 'turf': turf, 'msg': rmessage})
    else:
        return render (request, "adminpages/LoginUser.html")

def Userconfirm(request,turfid):
    if 'userlog_id' in request.session:
        userid = request.session['userlog_id']
        userlog = Userlist.objects.get(id = userid)
        turf_details = Managerlist.objects.get(id = turfid)
        bmessage = ""
        if request.method == "POST":
            name = request.POST['us_name']
            contact = request.POST['us_contact']
            turf = request.POST['us_turf']
            cost = request.POST['us_cost']
            date = request.POST['us_date']
            start = request.POST['us_start']
            end = request.POST['us_end']
            tcost = request.POST['us_totalcost']
            bstatus = "Pending"
            pstatus = "Pending"
            booking = Bookings(b_name=name, b_contact=contact, b_turf=turf, b_cost=cost, b_date=date, b_tst=start, b_tend=end, b_tcost=tcost, b_status=bstatus, b_pstatus=pstatus,mn_id_id=turf_details.id, us_id_id=userid)
            booking.save()
            if booking:
                bmessage = "Booking Details Submitted."
            else:
                bmessage = "error"
        return render (request, "userpages/user_confbook.html", {'user': userlog, 'turfdetails': turf_details, 'msg': bmessage})
    else:
        return render (request, "adminpages/LoginUser.html")

def Userbookings(request):
    if 'userlog_id' in request.session:
        userid = request.session['userlog_id']
        userlog = Userlist.objects.get(id = userid)
        booking = Bookings.objects.filter(us_id_id = userid)
        return render (request, "userpages/user_bookings.html", {'user': userlog, 'bookings': booking})
    else:
        return render (request, "adminpages/LoginUser.html")

def Userpayment(request):
    if 'userlog_id' in request.session:
        return render (request, "userpages/user_pymnt.html")
    else:
        return render (request, "adminpages/LoginUser.html")

def Userfeedback(request):
    if 'userlog_id' in request.session:
        userid = request.session['userlog_id']
        userlog = Userlist.objects.get(id = userid)
        fmessage = ""
        if request.method == "POST":
            name = request.POST['fname']
            email = request.POST['fmail']
            contact = request.POST['fcontact']
            desc = request.POST['fdesc']
            feedback = Feedbacks(f_name = name, f_email = email, f_contact = contact, f_message = desc)
            feedback.save()
            if feedback:
                fmessage = "Message recorded successfully"
            else:
                fmessage = "error"    
        return render (request, "userpages/user_feedbck.html", {'user': userlog, 'msg': fmessage})
    else:
        return render (request, "adminpages/LoginUser.html")

def Usereditprofile(request,edit_id):
    if 'userlog_id' in request.session:
        if request.method == "POST":
            name = request.POST['name1']
            email = request.POST['email1']
            phone = request.POST['phone1']
            username = request.POST['username1']
            password = request.POST['password1']
            Userlist.objects.filter(id = edit_id).update(user_name = name, user_email = email, user_mobile = phone, user_username = username, user_password = password)
            return redirect ('user:uhomepage')
        else:
            user_data = Userlist.objects.get(id = edit_id)
            return render (request, "userpages/userprofile2.html", {'usdata': user_data})
    else:
        return render (request, "adminpages/LoginUser.html")

TMS_user/templates/userpages/user_pymnt.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment Gateway</title>
    <link href="{% static '/css/proj3.css' %}" rel="stylesheet"/>
    <link rel = "icon" href = "https://cdn-icons-png.flaticon.com/128/726/726488.png" width="25px" height="20px" type = "image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
  <div class="container payment-form">
    <div class="block-heading">
      <h2>Payment Details</h2>
      <p>Make payment for the turf you have selected.</p>
    </div>
    <form>
      <div class="products">
        <h3 class="title">Checkout</h3>
        <div class="item">
          <span class="price">Rs ---</span>
          <p class="item-name">Emirates Turf</p>
          <p class="item-description">Kannur ; 9-10 PM</p>
        </div>
        <div class="card-details">
          <h3 class="title">Card Details</h3>
          <div class="row">
            <div class="form-group col-sm-7">
              <label for="card-holder">Card Holder</label>
              <input id="card-holder" type="text" class="form-control" placeholder="Card Holder" aria-label="Card Holder" aria-describedby="basic-addon1">
            </div>
            <div class="form-group col-sm-5">
              <label for="">Expiration Date</label>
              <div class="input-group expiration-date">
                <input type="text" class="form-control" placeholder="MM" aria-label="MM" aria-describedby="basic-addon1">
                <span class="date-separator">/</span>
                <input type="text" class="form-control" placeholder="YY" aria-label="YY" aria-describedby="basic-addon1">
              </div>
            </div>
            <div class="form-group col-sm-8">
              <label for="card-number">Card Number</label>
              <input id="card-number" type="text" class="form-control" placeholder="Card Number" aria-label="Card Holder" aria-describedby="basic-addon1">
            </div>
            <div class="form-group col-sm-4">
              <label for="cvc">CVC</label>
              <input id="cvc" type="text" class="form-control" placeholder="CVC" aria-label="Card Holder" aria-describedby="basic-addon1">
            </div>
            <div class="form-group col-sm-12">
              <button type="button" class="btn btn-primary btn-block">Proceed</button>
            </div>
        </div>
      </div>
    </form>
    </div>
    <div id="timedif">

    </div>
    <input type="time" class="form-control" name="eq_pf" id="eq_pf" value="">
      
    <input type="time" class="form-control" name="eq_pt" id="eq_pt" value="">
    <button id="btn">
    Difference
    </button>
</body>

<script>
  $(function() {

});
$("#btn").click(function() {
  var from = $("#eq_pf").val();
  var to = $("#eq_pt").val();

  var diff = (new Date("1970-1-1 " + from) - new Date("1970-1-1 " + to)) / 1000 / 60 / 60;
  $("#timedif").html(diff.toString());
});

</script>
</html>

TMS_user/templates/userpages/user_searchlist.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Turfs</title>
    <link href="{% static '/css/proj3.css' %}" rel="stylesheet"/>
    <link rel = "icon" href = "https://cdn-icons-png.flaticon.com/128/954/954591.png" width="25px" height="20px" type = "image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js">
</head>
<body>
  <header>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-dark" style=" background-color: #0a0a0a">
        <a class="navbar-brand" href="{% url 'appadmin:homepage2' %}"><img src="{% static '/images/amalgamation_logo.jpg' %}" alt="" width="30" height="40"><b> Amalgamation</b></a>
      </nav>
    </div>
  </header>  
  <div class="welcome_user">
    <nav class="navbar navbar-light">
      <a class="navbar-brand">Hello {{user.user_name}}</a>
      <form class="form-inline">
        <li><a href="{% url 'appadmin:homepage2' %}">Home</a></li>
        <li><a href="{% url 'user:uhomepage' %}">Dashboard </a></li>
        <a href="{% url 'appadmin:userlogout' %}"><button class="btn btn-outline-success my-2 my-sm-0" type="button">Logout</button></a>
      </form>
    </nav>
  </div>
  <div class="container-fluid turfdetails">
    <div class="container col-lg-6 col-md-6 col-sm-12 p-0 searchbar">
      <div class=" locationsearch">
        <label for=""><b>Search by Location: </b></label>
        <select name="turfs" id="locations"><br>
          <option value="default">--Select--</option>
          {% for turf_ in turf %}
          <option value="{{turf_.id}}">{{turf_.man_turfloc}}</option>
          {% endfor %}
        </select>
      </div>
      <form autocomplete="off" action="{% url 'user:usearchlist' %}" method="post">
        {% csrf_token %}
        <input type="search" name="search" class="search" id="form1" name="form-control">
        <ul class="list"></ul>         
        <input type="submit" class="btn btn-primary searchbut" value="Search">  <input type="reset" class="btn btn-dark" value="Reset">
      </form>
    </div>  
    {% for turf_ in turf1 %}
    <div class="row row-cols-1 row-cols-md-2 searchturf">
      <div class="col mb-4">
        <div class="card">
          <img src="{{imageturf.images.url}}" class="card-img-top" alt="...">
          <div class="card-body">
            <h4 class="card-title">{{turf_.man_turfname}} Turf</h4>
            <p class="card-text">Location: {{turf_.man_turfloc}} </p> <br>
            <a href="{% url 'user:uconfirmturf' turf_.id %}"><button type="button" class="btn btn book">Book Now</button></a>
            <!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#t1{{turf_.pk}}"><i class="fa-sharp fa-solid fa-circle-info"></i></button> -->
            <a href="{% url 'user:usearchdetail' turf_.id %}"><button type="button" class="btn btn-primary"><i class="fa-sharp fa-solid fa-circle-info"></i></button></a>
            <a href="{% url 'user:ureview' turf_.id %}"><button type="button" class="btn btn book">Review</button></a>
              <div class="modal fade" id="t1{{turf_.pk}}" tabindex="-1" role="dialog" aria-labelledby="t1{{turf_.pk}}-label" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" role="document">
                  <div class="modal-content confbutton">
                    <div class="modal-header ">
                      <h5 class="modal-title" id="t1{{turf_.pk}}-label">{{turf_.man_turfname}} Turf</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <div id="carouselExampleControls1" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                          {% for image in imageturf %}
                          <div class="carousel-item active">
                            <img src="{{image.images.url}}" class="d-block w-100" alt="..." style="width: 100%; height: 400px;">
                          </div>
                          <div class="carousel-item">
                            <img src="{{image.images.url}}" class="d-block w-100" alt="..." style="width: 100%; height: 400px;">
                          </div>
                          <div class="carousel-item">
                            <img src="{{image.images.url}}" class="d-block w-100" alt="..." style="width: 100%; height: 400px;">
                          </div>
                          {% endfor %}
                        </div>
                        <button class="carousel-control-prev" type="button" data-target="#carouselExampleControls1" data-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="sr-only">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-target="#carouselExampleControls1" data-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="sr-only">Next</span>
                        </button>
                      </div>
                      <br>
                      <br>Location - {{turf_.man_turfloc}}
                      <br>Cost - Rs {{turf_.turf_cost}} per Hour
                      <br>{{turf_.turf_desc}}
                      <br>------------------------------------------------------------
                      <br><u><b>Reviews</b></u><br>
                      {% for user in users %}
                      <br>{{user.review_user}} - "{{user.review_message}}"
                      <br>
                      {% endfor %}
                    </div>
                    <div class="modal-footer">
                      <a href="{% url 'user:uconfirmturf' turf_.id %}"><button type="button" class="btn btn book">Book Now</button></a>
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>   
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="container- my-3">
    <footer class="text-center text-lg-start text-white" style="background:linear-gradient(to right, #568EE3, #B368ED);">
      <div class="container p-4 pb-0">
        <section class="">
          <div class="row">
            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">
                About Us
              </h6>
              <p style="font-family: Arial, Helvetica, sans-serif;">
                We are one of the leading online turf booking platform based in Kerala.
                Choose the turf of your choice and enjoy the time with your friends - We can make it simple for you.
                So join us and have the blast!!! 
              </p>
            </div>
            <hr class="w-100 clearfix d-md-none" />
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Quick Links</h6>
              <p class="Footers">
                <a class="text-white" href="{% url 'appadmin:homepage2' %}">Home</a>
              </p>
              <p>
                <a class="text-white" href="">Login</a>
              </p>
              <p>
                <a class="text-white" href="{% url 'user:usearchturf' %}">Book Now</a>
              </p>
            </div>
            <hr class="w-100 clearfix d-md-none" />
            <hr class="w-100 clearfix d-md-none" />
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Contact Us</h6>
              <p><i class="fas fa-pen mr-3"></i> Amalgamation</p>
                <p><i class="fas fa-home mr-3"></i> Taliparamba, Kannur, Kerala</p>
                <p><i class="fas fa-envelope mr-3"></i> amalg@gmail.com</p>
                <p><i class="fas fa-phone mr-3"></i> + 7012 39 1939</p>
            </div>
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Follow us</h6>
  
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #3b5998"
                 href="#!"
                 role="button">
                 <i class="fab fa-facebook-f"></i>
              </a>
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #55acee"
                 href="#!"
                 role="button">
                 <i class="fab fa-twitter"></i>
              </a>
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #dd4b39"
                 href="#!"
                 role="button">
                 <i class="fab fa-google"></i>
              </a>
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #ac2bac"
                 href="#!"
                 role="button">
                 <i class="fab fa-instagram"></i>
              </a>
              <a
                 class="btn btn-primary btn-floating m-1"
                 style="background-color: #0082ca"
                 href="#!"
                 role="button">
                 <i class="fab fa-linkedin-in"></i>
              </a>
            </div>
          </div>
        </section>
      </div>
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2022 Copyright:
        <a class="text-white" href="#">Amalgamation.com</a>
      </div>
    </footer>
  </div>
   
    <script src="{% static '/javascript/rating.js' %}"></script>
    <script src="{% static '/javascript/user.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>