TMS_TurfManager/urls.py
from django.urls import path
from . import views
app_name = 'manager'

urlpatterns = [
    path('ManagerHome/', views.Managerhome, name = "mhomepage"),
    path('ManagerTurf/', views.Managerturf, name = "mturf"),
    path('ManagerConfirm/', views.Managerconfirm, name = "mbookconfirm"),
    path('ManagerCancel/', views.Managercancel, name = "mcancelbook"),
    path('ManagerAccept/', views.Manageraccept, name = "macceptbook"),
    path('ManagerBookings/', views.Managerbookings, name = "mbookhistory"),
    path('ManagerReviews/', views.Managerreviews, name = "mturfreview"),
    path('ManagerEditturf/<int:turf_id>', views.Managereditturf, name = "mturfedit"),
    path('ManagerAddimage/', views.Manageraddimage, name = "mturfimage"),
    path('ManagerEditprofile/<int:edit_id>', views.Managereditprofile, name = "meditprofile"),
]

TMS_admin/urls.py
from django.urls import path
from . import views
app_name = 'appadmin'

urlpatterns = [
    path('Amalgamation/', views.Homepage, name = "homepage"),
    path('Amalgamation1/', views.Homepage2, name = "homepage2"),
    path('LoginUser/', views.Loginuser, name = "loginuser"),
    path('LoginManager/', views.Loginmanager, name = "loginmanager"),
    path('UserLogout/', views.Userlogout, name= "userlogout"),
    path('ManagerLogout/', views.Managerlogout, name= "managerlogout"),
    path('Contact/', views.Turfrequest, name = "turfrequest"),
    path('Register/', views.Register, name = "register"),
    path('Adminlogin/', views.AdminLogin, name = "admlogin"),
    path('Adminhome/', views.AdminHome, name = "admhome"),
    path('AdminLogout/', views.Adminlogout, name= "admlogout"),
    path('AdminAddmngr/<int:mn_id>', views.Adminaddmngr, name = "admaddmngr"),
    path('Adminrejectmngr/<int:mn_id>', views.Adminrejectmngr, name = "admreject"),
    path('AdminAddturf/', views.Adminaddturf, name = "admaddturf"),
    path('AdminFeedbacks/', views.Adminfeedbacks, name = "admfeedback"),
    path('AdminManagers/', views.Adminmanagers, name = "admmanagers"),
    path('AdminRejManagers/', views.Adminrejmanagers, name = "admrejmanagers"),
    path('AdminUsers/', views.Adminusers, name = "admusers"),
    path('AdminTurfs/', views.Adminturfs, name = "admturfs"),
    path('Adminimages/<int:turfid>', views.Adminviewimages, name = "admturfimages"),
    path('AdminRequests/', views.Adminrequests, name = "admrequests"),
]

TMS_user/urls.py
from django.urls import path
from . import views
app_name = 'user'

urlpatterns = [
    path('UserHome/', views.Userhome, name = "uhomepage"),
    path('UserSearch/', views.Usersearch, name = "usearchturf"),
    path('UserSearchlist/', views.Searchlist, name = "usearchlist"),
    path('UserSearchDetail/<int:turfid>', views.Usersearchdetail, name = "usearchdetail"),
    path('UserConfirm/<int:turfid>', views.Userconfirm, name = "uconfirmturf"),
    path('UserReview/<int:turfid>', views.Userreview, name = "ureview"),
    path('UserBookings/', views.Userbookings, name = "ubookings"),
    path('UserPayment/', views.Userpayment, name = "upayment"),
    path('UserFeedback/', views.Userfeedback, name = "ufeedback"),
    path('UserEditprofile/<int:edit_id>', views.Usereditprofile, name = "ueditprofile"),
]

TurfManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("TMS_admin/", include ('TMS_admin.urls')),
    path("TMS_TurfManager/", include ('TMS_TurfManager.urls')),
    path("TMS_user/", include ('TMS_user.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TMS_admin/models.py
from django.db import models

# Create your models here.
class Adminlog(models.Model):
    admin_name = models.TextField(max_length=50, db_column='name')
    admin_pass = models.TextField(max_length=50, db_column='pswd')

    class Meta:
        db_table="adminlogin"	

class Managerlist(models.Model):
    man_name = models.TextField(max_length=50, db_column='name')
    man_email = models.TextField(max_length=50, db_column='email')
    man_contact = models.TextField(max_length=50, db_column='contact')
    man_turfname = models.TextField(max_length=50, db_column='turf')
    man_turfloc = models.TextField(max_length=50, db_column='loc')
    man_username = models.TextField(max_length=50, db_column='usnam')
    man_password = models.TextField(max_length=50, db_column='pswd')
    man_status = models.TextField(max_length=50, db_column='status')    
    turf_desc = models.TextField(max_length=500, null=True, db_column='desc')
    turf_cost = models.TextField(max_length=50, null=True, db_column='cost')

    class Meta:
        db_table="managerlist"

class Userlist(models.Model):
    user_name = models.TextField(max_length=50, db_column='name')
    user_email = models.TextField(max_length=50, db_column='email')
    user_mobile = models.TextField(max_length=50, db_column='mobile')
    user_username = models.TextField(max_length=50, db_column='usnam')
    user_password = models.TextField(max_length=50, db_column='pswd')
    user_confpassword = models.TextField(max_length=50, db_column='cpswd')    

    class Meta:
        db_table="userlist"

class Turfimages(models.Model):
    manager_id = models.ForeignKey(Managerlist, on_delete=models.CASCADE, db_column='m_id')
    images = models.ImageField(upload_to='images/', db_column='images')

    class Meta:
        db_table="turfimages"

TMS_admin/views.py
from django.shortcuts import render, redirect
from . models import *
from TMS_user.views import *
from TMS_TurfManager.views import *

# Create your views here.

def Homepage(request):
    return render (request, "adminpages/home.html")

def Homepage2(request):
    return render (request, "adminpages/home2.html")

def AdminLogin(request):
    if request.method == "POST":
        adminname = request.POST['adname']
        adminpass = request.POST['adpass']
        try:
            admin_log = Adminlog.objects.get(admin_name = adminname, admin_pass = adminpass)
            request.session['adlog_id'] = admin_log.id
            return redirect ('appadmin:admhome')
        except Adminlog.DoesNotExist:
            return render (request, "adminpages/admin_login.html", {'failed':'Login credentials incorrect'}) 
    return render (request, "adminpages/admin_login.html")

def AdminHome(request):
    if 'adlog_id' in request.session:
        return render (request, "adminpages/admin_profile.html")
    else:
        return render (request, "adminpages/admin_login.html")
    
def Adminlogout(request):
    del request.session['adlog_id']
    return redirect ('appadmin:admlogin')

def Adminaddmngr(request,mn_id):
    if 'adlog_id' in request.session:
        if request.method == "POST":
            m_name = request.POST['mngrname']
            m_contact = request.POST['mngrcontact']
            m_email = request.POST['mngrmail']
            m_turfname = request.POST['mngrturf']
            m_turfloc = request.POST['mngrturfloc']
            m_username = request.POST['mngrid']
            m_password = request.POST['mngrpass']
            m_status = 'accepted'
            Managerlist.objects.filter(id=mn_id).update(man_name=m_name, man_email=m_email, man_contact=m_contact, man_turfname = m_turfname, man_turfloc=m_turfloc, man_username=m_username, man_password=m_password, man_status = m_status)
            return redirect ('appadmin:admrequests')
        else:    
            mng_data = Managerlist.objects.get(id=mn_id)
            return render (request, "adminpages/addmanager.html", {'mng': mng_data})
            
    else:
        return render (request, "adminpages/admin_login.html")

def Adminrejectmngr(request,mn_id):
    if 'adlog_id' in request.session:
        man_status = 'rejected'
        Managerlist.objects.filter(id=mn_id).update(man_status = man_status)
        return redirect ('appadmin:admrequests')
    else:
        return render (request, "adminpages/admin_login.html")

def Adminaddturf(request):
    if 'adlog_id' in request.session:
        return render (request, "adminpages/addturf.html")
    else:
        return render (request, "adminpages/admin_login.html")
    
def Adminfeedbacks(request):
    if 'adlog_id' in request.session:
        us_feed = Feedbacks.objects.all().order_by('id')
        return render (request, "adminpages/admin_feed.html", {'feed':us_feed})
    else:
        return render (request, "adminpages/admin_login.html")
    
def Adminmanagers(request):
    if 'adlog_id' in request.session:
        mr_data = Managerlist.objects.filter(man_status = 'accepted').order_by('id')
        return render (request, "adminpages/admin_manager.html", {'m_data':mr_data})
    else:
        return render (request, "adminpages/admin_login.html")
    
def Adminrejmanagers(request):
    if 'adlog_id' in request.session:
        rmr_data = Managerlist.objects.filter(man_status = 'rejected').order_by('id')
        return render (request, "adminpages/admin_manager_reject.html", {'rm_data':rmr_data})
    else:
        return render (request, "adminpages/admin_login.html")    

def Adminusers(request):
    if 'adlog_id' in request.session:
        user_data = Userlist.objects.all().order_by('id')
        return render (request, "adminpages/admin_users.html", {'u_data':user_data})
    else:
        return render (request, "adminpages/admin_login.html")  

def Adminturfs(request):
    if 'adlog_id' in request.session:
        turf_data = Managerlist.objects.filter(man_status = 'accepted').order_by('id')
        return render (request, "adminpages/admin_turf.html", {'t_data':turf_data})
    else:
        return render (request, "adminpages/admin_login.html")
    
def Adminviewimages(request,turfid):
    if 'adlog_id' in request.session:
        turf_data = Managerlist.objects.get(id = turfid)
        turfimages = Turfimages.objects.filter(manager_id = turfid)
        return render (request, "adminpages/admin_turfdetails.html", {'t_data':turf_data, 'image': turfimages})
    else:
        return render (request, "adminpages/admin_login.html")   

def Adminrequests(request):
    if 'adlog_id' in request.session:
        request_data = Managerlist.objects.filter(man_status = 'Pending')
        return render (request, "adminpages/admin_requests.html", {'req_data':request_data})
    else:
        return render (request, "adminpages/admin_login.html")
    
def Register(request):
    regmessage = ""
    if request.method == "POST":
        u_name = request.POST['regname']
        u_email = request.POST['regmail']
        u_number = request.POST['regnumber']
        u_username = request.POST['regusername']
        u_password = request.POST['regpass']
        u_confpassword = request.POST['regconfpass']
        reg_data = Userlist(user_name = u_name, user_email = u_email, user_mobile = u_number, user_username = u_username, user_password = u_password, user_confpassword = u_confpassword)
        reg_data.save()
        if reg_data:
            regmessage = "Registered successfully. Now you can login to your account."
        else:
            regmessage = "error"
    return render (request, "adminpages/Register.html", {'reg': regmessage})

def Loginuser(request):
    if request.method == 'POST':
        username = request.POST['logusername']
        password = request.POST['loguserpass']
        try:
            user = Userlist.objects.get(user_username = username, user_password = password)
            request.session['userlog_id'] = user.id
            return redirect('user:uhomepage')
        except Userlist.DoesNotExist:
            return render (request, "adminpages/LoginUser.html", {'fail':'No user found.'})
    return render (request, "adminpages/LoginUser.html")     

def Userlogout(request):
    del request.session['userlog_id']
    # return render (request, "adminpages/LoginUser.html", {'logout':'You have successfully logged out.'})
    return redirect ('appadmin:loginuser')

def Loginmanager(request):
    if request.method == 'POST':
        username = request.POST['logmngrusername']
        password = request.POST['logmngrpass']
        try:
            manager = Managerlist.objects.get(man_username = username, man_password = password)
            request.session['managerlog_id'] = manager.id
            if manager.man_status == 'accepted':
                return redirect('manager:mhomepage')
            else:
                return render (request, "adminpages/LoginManager.html", {'fail':'Invalid Login credentials!!!'})
        except Managerlist.DoesNotExist:
            return render (request, "adminpages/LoginManager.html", {'fail':'No Manager found.'})
    return render (request, "adminpages/LoginManager.html")  

def Managerlogout(request):
    del request.session['managerlog_id']
    # return render (request, "adminpages/LoginManager.html", {'logout':'You have successfully logged out.'})
    return redirect ('appadmin:loginmanager')

def Turfrequest(request):
    rmessage = ""
    if request.method == "POST":
        mng_name = request.POST['treqname']
        mng_email = request.POST['treqmail']
        mng_contact = request.POST['treqnumber']
        mng_turfname = request.POST['treqturfname']
        mng_turfloc = request.POST['treqturfloc']
        mng_username = request.POST['treqmngrusname']
        mng_pass = request.POST['treqmngrpass']
        mng_status = "Pending"
        mng_data = Managerlist(man_name=mng_name, man_email=mng_email, man_contact=mng_contact, man_turfname=mng_turfname, man_turfloc=mng_turfloc, man_username=mng_username, man_password=mng_pass, man_status=mng_status)
        mng_data.save()
        if mng_data:
            rmessage = "Thank you for entering the details. Please wait for the confirmation."
        else:
            rmessage = "error"    
    return render (request, "adminpages/turf_request.html", {'req': rmessage})  

TMS_admin/templates/adminpages/addmanager.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Manager</title>
    <link href="{% static '/css/proj.css' %}" rel="stylesheet"/>
    <link rel = "icon" href = "https://cdn-icons-png.flaticon.com/128/1167/1167204.png" width="25px" height="20px" type = "image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
  <header>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-dark" style=" background-color: #0a0a0a">
          <a class="navbar-brand" href=""><img src="{% static '/images/amalgamation_logo.jpg' %}" alt="" width="30" height="40"><b> Amalgamation</b></a>
        </nav>
    </div>
  </header>  
  <div class="welcome_user">
    <nav class="navbar navbar-light">
      <a class="navbar-brand">Hello Admin</a>
      <form class="form-inline">
        <div class="input-group mt-2 mb-2">
          <div class="input-group-prepend">
            <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-user"></i> Abhijith
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'appadmin:admlogout' %}">Logout</a>
            </div>
          </div>
        </div>   
      </form>
    </nav>
  </div>
  <div class="container-fluid addturf">
    <div class="row">
      <div class="col-md-2 sm-2 xs-2 sidebar ">
        <h4>Admin Panel</h4>
        <a href="{% url 'appadmin:admhome' %}">Dashboard</a>
        <a href="{% url 'appadmin:admturfs' %}">Turfs</a>
        <a href="{% url 'appadmin:admusers' %}">Users</a>
        <a href="{% url 'appadmin:admmanagers' %}">Managers</a>
        <a href="{% url 'appadmin:admrequests' %}">Turf Requests</a>
        <a href="{% url 'appadmin:admfeedback' %}">Feedbacks</a>
        <a href="{% url 'appadmin:admlogout' %}">Logout</a>
      </div>       
      <div class="col-sm-10 col-md-10 col-xs-10 addturf1">
        <form action="{% url 'appadmin:admaddmngr' mng.id %}" method="post">
          {% csrf_token %}
          <div class="heading1">
            <h1>Add Manager Details</h1><br>
          </div>
          <div class="form-group">
            <label for="">Manager Name</label>
            <input type="text" name="mngrname" value="{{mng.man_name}}" id="mgname" placeholder=""><br>
            <span class="adderror" id="admgmanagername"></span><br>
          </div>
          <div class="form-group">
            <label for="">Contact Number</label>
            <input type="tel" name="mngrcontact" value="{{mng.man_contact}}" id="mgphone" placeholder=""><br>
            <span class="adderror" id="admgmanagerphone"></span><br>
          </div>
          <div class="form-group">
            <label for="">E-mail</label>
            <input type="email" name="mngrmail" value="{{mng.man_email}}" id="mgmail" placeholder=""><br>
            <span class="adderror" id="admgmanagermail"></span><br>
          </div>
          <div class="form-group">
            <label for="">Turf Assigned</label>
            <input type="text" name="mngrturf" value="{{mng.man_turfname}}" id="mgturfname" placeholder=""><br>
            <span class="adderror" id="admgturfname"></span><br>
          </div>
          <div class="form-group">
            <label for="">Turf Location</label>
            <input type="text" name="mngrturfloc" value="{{mng.man_turfloc}}" id="mgturfloc" placeholder=""><br>
            <span class="adderror" id="admgturfloc"></span><br>
          </div>
          <div class="form-group">
            <label for="">Username</label>
            <input type="text" name="mngrid" value="{{mng.man_username}}" id="mgid" placeholder=""><br>
            <span class="adderror" id="admgmanagerid"></span><br>
          </div>
          <div class="form-group">
            <label for="">Password</label>
            <input type="password" name="mngrpass" value="{{mng.man_password}}" id="mgpassword" placeholder=""><br>
            <span class="adderror" id="admgmanagerpass"></span><br>
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-block submit">Add Manager</button>
          </div>   
          <br><p>{{add}}</p> 
        </form>
      </div> 
    </div>    
  </div>               
  <div class="container-">
    <footer class="text-center text-lg-start text-white" style="background:linear-gradient(to right, #568EE3, #B368ED);">
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2022 Copyright:
        <a class="text-white" href="#">Amalgamation.com</a>
      </div>
    </footer>
  </div>
   
    <script src="{% static '/javascript/adminaddmngr.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>

TMS_admin/templates/adminpages/admin_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
    <link rel = "icon" href = "https://media.istockphoto.com/id/954805524/vector/gear-icon-vector-male-user-person-profile-avatar-symbol-on-cog-wheel-for-settings-and.jpg?b=1&s=612x612&w=0&k=20&c=Axm722RdsqLhq7qOuRStFJGCRCn2yIjW_CwUsThUr08=" width="25px" height="20px" type = "image/x-icon">
    <link href="{% static '/css/proj.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
</head>
<body class="body">
    <a href="{% url 'appadmin:homepage' %}" class="button"><i class="fa-solid fa-house-user"></i>Home Page</a>
    <div class="container adminlogin">
        <div class="adlog">
            <form action="" method="post">
                {% csrf_token %}
                <h2>Hi Admin, Login Now</h2>
                <input type="text" name="adname" id="adname" placeholder="Admin Name">
                <span class="adminerror" id="adminname"></span>
                <input type="password" name="adpass" id="adpass" placeholder="Password">
                <span class="adminerror" id="adminpass"></span>
                <button onclick="return log_admin()" type="submit" class="btn btn-block signin">Sign In</button><br><br>
                <p style="color: red;">{{failed}}</p>
            </form>
        </div>
        <div class="image2">
            <img src="https://t3.ftcdn.net/jpg/01/57/34/62/360_F_157346244_A6Oml9kXsQdK3WaVVg91UnzheU0YeFpe.jpg" alt="">
        </div>
    </div>

    <script src="{% static '/javascript/admin.js' %}"></script>
</body>
</html>

TMS_admin/templates/adminpages/admin_requests.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Turf Requests</title>
    <link href="{% static '/css/proj.css' %}" rel="stylesheet"/>
    <link rel = "icon" href = "https://cdn-icons-png.flaticon.com/128/6216/6216306.png" width="25px" height="20px" type = "image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
</head>
<body>
  <header>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-dark" style=" background-color: #0a0a0a">
          <a class="navbar-brand" href=""><img src="{% static '/images/amalgamation_logo.jpg' %}" alt="" width="30" height="40"><b> Amalgamation</b></a>
        </nav>
    </div>
  </header>  
  <div class="welcome_user">
    <nav class="navbar navbar-light">
      <a class="navbar-brand">Hello Admin</a>
      <form class="form-inline">
        <div class="input-group mt-2 mb-2">
          <div class="input-group-prepend">
            <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-user"></i> Abhijith
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'appadmin:admlogout' %}">Logout</a>
            </div>
          </div>
        </div>   
      </form>
    </nav>
  </div>
  <div class="container-fluid feedback">
    <div class="row">
      <div class="col-md-2 sm-2 sidebar ">
        <h4>Admin Panel</h4>
        <a href="{% url 'appadmin:admhome' %}">Dashboard</a>
        <a href="{% url 'appadmin:admturfs' %}">Turfs</a>
        <a href="{% url 'appadmin:admusers' %}">Users</a>
        <a href="{% url 'appadmin:admmanagers' %}">Managers</a>
        <a href="{% url 'appadmin:admrequests' %}">Turf Requests</a>
        <a href="{% url 'appadmin:admfeedback' %}">Feedbacks</a>
        <a href="{% url 'appadmin:admlogout' %}">Logout</a>
      </div>
      <div class="col-md-10 sm-10 feedback1">
        <h4>Turf Requests</h4><br>
        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">E-mail</th>
              <th scope="col">Contact No</th>
              <th scope="col">Turf</th>
              <th scope="col">Location</th>
              <th scope="col">Username</th>
              <th scope="col">Password</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            {% for req in req_data %}
            <tr>
              <th scope="row">{{req.id}}</th>
              <td>{{req.man_name}}</td>
              <td>{{req.man_email}}</td>
              <td>{{req.man_contact}}</td>
              <td>{{req.man_turfname}}</td>
              <td>{{req.man_turfloc}}</td>
              <td>{{req.man_username}}</td>
              <td>{{req.man_password}}</td>
              <td><a href="{% url 'appadmin:admaddmngr' req.id %}"><button type="button" class="btn btn-primary"><i class="fa-sharp fa-solid fa-check-circle"></i></button></a>
                  <a href="{% url 'appadmin:admreject' req.id %}"><button type="submit" class="btn btn-primary"><i class="fa-sharp fa-solid fa-times-circle"></i></button></a> 
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>  
  </div>
  <div class="container-">
    <footer class="text-center text-lg-start text-white" style="background:linear-gradient(to right, #568EE3, #B368ED);">
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2022 Copyright:
        <a class="text-white" href="#">Amalgamation.com</a>
      </div>
    </footer>
  </div>
   
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>